apiVersion: v1
kind: Service
metadata:
  name: domain-user-service
spec:
  type: ClusterIP
  selector:
    app: user-ms
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-users
  labels:
    account: domain-user-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-user-deployment
  namespace: default
  annotations:
    sidecar.istio.io/inject: "true"
  labels:
    app: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: user-ms
    spec:
      serviceAccountName: demo-users
      containers:
        - name: user-ms
          image: ssuazaa08/domain-user-service
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              value: postgres-service
          ports:
            - containerPort: 8080