apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-invoice-deployment
  namespace: default
  labels:
    app: invoice-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
        - name: invoice-service
          image: ssuazaa08/domain-invoice-service
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              value: postgres-service
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: domain-invoice-service
spec:
  type: ClusterIP
  selector:
    app: invoice-service
  ports:
    - protocol: TCP
      port: 8080