apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: demo
    tier: postgres
data:
  pgdata: |
    POSTGRES_DB: invoice
    PGDATA: /var/lib/postgresql/data/pgdata

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: aW52b2ljZQ==
  POSTGRES_PASSWORD: MTIzNA==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
  labels:
    app: postgres-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-service
  template:
    metadata:
      labels:
        app: postgres-service
    spec:
      containers:
        - name: postgres
          image: postgres:14.2-alpine
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
              name: postgredb
#          volumeMounts:
#            - mountPath: /var/lib/postgresql
#              name: postgredb
#      volumes:
#        - name: postgredb
#          persistentVolumeClaim:
#            claimName: postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
#  type: NodePort
  selector:
    app: postgres-service
  ports:
    - protocol: TCP
      port: 5432